import axios from "../../../api/axios.news";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../../../styles/regions.module.sass";
export default function regions() {
  const [regions, setRegions] = useState([]);
  useEffect(() => {
    const getRegions = async () => {
      try {
        const res = await axios.get(`/regions?populate=image`);
        if (!res.data) {
          throw new Error();
        }
        setRegions(res.data.data);
      } catch (error) {}
    };
    getRegions();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Регионы</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.content}>
        <h2 className={styles.main__title}>Регионы</h2>
        <ul className={styles.contentList}>
          {regions.map(
            ({
              region,
              number,
              team,
              regionMainPerson,
              email,
              numPeople,
              id,
            }) => {
              return (
                <li className={styles.contentList__item} key={id}>
                  <h4 className={styles.contentList__title}>{region}</h4>
                  <p>
                    <b className={styles.boldText}>
                      Региональный представитель:
                    </b>
                    <span> {regionMainPerson}</span>
                  </p>
                  <p>
                    <b className={styles.boldText}>Кол-во команд: </b>
                    {team}
                  </p>
                  <p>
                    <b className={styles.boldText}>Кол-во занимающихся: </b>
                    {numPeople}
                  </p>
                  <p>
                    <b className={styles.boldText}>Контактный тел: </b>+{number}
                  </p>
                  <p>
                    <b className={styles.boldText}>Электронный адрес: </b>
                    {email}
                  </p>
                </li>
              );
            }
          )}
        </ul>
      </div>
    </div>
  );
}
