import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../../styles/vacancies/vacancies.module.sass";
import axios from "../../api/axios.news";
import Error from "../../components/Error/Error";
import Loader from "../../components/Loader/Loader";

export default function Vacancies() {
  const [data, setData] = useState(null);
  useEffect(() => {
    const getData = async () => {
      try {
        const res = await axios.get(`/vakansiis`);
        if (!res.data || res.data.data.length === 0) {
          throw new Error();
        }
        setData(res.data.data);
      } catch (error) {
        setData("Error");
      }
    };
    getData();
  }, []);
  if (data) {
    if (data === "Error") {
      return (
        <div className={styles.error__contaner}>
          <Head>
            <title>Вакансии</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className={styles.error__item}>
            <img src="/images/icons/ball.png" alt="notFind" />
            <h1 className={styles.mainError__title}>
              На данный момент нет открытых вакансий
            </h1>
          </div>
        </div>
      );
    } else {
      return (
        <div className={styles.container}>
          <Head>
            <title>Вакансии</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <h1 className={styles.main__title}>Вакансии</h1>
          <div className={styles.content}>
            {data.map(({ post, des, number, id }) => {
              return (
                <div key={id} className={styles.content__item}>
                  <p className={styles.contentItem__post}>{post}</p>
                  <p className={styles.contentItem__des}>{des}</p>
                  <p className={styles.contentItem__number}>+{number}</p>
                </div>
              );
            })}
          </div>
        </div>
      );
    }
  } else {
    return <Loader />;
  }
}
