import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../../styles/vacancies/vacancies.module.sass";
import axios from "../../api/axios.news";

export default function vacancies() {
  const [data, setData] = useState([]);
  useEffect(() => {
    const getData = async () => {
      try {
        const res = await axios.get(`/vakansiis`);
        if (!res.data) {
          throw new Error();
        }
        setData(res.data.data);
      } catch (error) {}
    };
    getData();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Вакансии</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.main__title}>Вакансии</h1>
      <div className={styles.content}>
        {data.map(({ post, des, number, id }) => {
          return (
            <div key={id} className={styles.content__item}>
              <p className={styles.contentItem__post}>{post}</p>
              <p className={styles.contentItem__des}>{des}</p>
              <p className={styles.contentItem__number}>+{number}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
