import axios from "../../api/axios.news";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../../styles/futsal/futsal.module.sass";
import Link from "next/link";

export default function futsal() {
  const [data, setData] = useState([]);
  useEffect(() => {
    const getData = async () => {
      try {
        const res = await axios.get(`/futzals?populate=image`);
        if (!res.data) {
          throw new Error();
        }
        setData(res.data.data);
      } catch (error) {}
    };
    getData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Футзал</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.main__title}>Футзал</h1>
      <p className={styles.main__content}>
        Соревнования по футболу, как и в любом другом виде спорта — важная
        составляющая игры. Соревнование организуется федерацией, для каждого
        турнира составляется регламент, в котором обычно определяют состав
        участников, схему турнира, правила определения победителя при равенстве
        очков и какие-то отклонения от правил, например количество замен.
        Соревнования делятся на внутренние и международные, которые в свою
        очередь разделяются на клубные и национальных сборных. Футбольные
        турниры собирают десятки тысяч зрителей на трибунах стадиона и
        многомиллионные аудитории по телевидению.
      </p>
      <div className={styles.pageLink__list}>
        {data.map(({ title, text, image, id }) => {
          return (
            <Link key={id} href={`/futsal/${id}`}>
              <a className={styles.pageLink__item}>
                <div className={styles.pageLink__image}>
                  <img src={image.url} alt={image.name} />
                </div>
                <h3 className={styles.pageLink__title}>{title}</h3>
              </a>
            </Link>
          );
        })}
      </div>
    </div>
  );
}
