import Head from "next/head";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import { nav } from "../../data/nav";
import styles from "../../styles/kfu.module.sass";

export default function kfu() {
  const [forLink, setForLink] = useState([]);
  useEffect(() => {
    const link = nav.find((item) => {
      return item.name.indexOf("КФС") > -1;
    });
    setForLink(link.doughter);
  }, []);
  return (
    <div className={styles.about__container}>
      <Head>
        <title>Кыргызский футбольный союз</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.about}>
        <h2 className={styles.aboutInner__title}>Кыргызский футбольный союз</h2>
        <p>
          <b>Кыргызский футбольный союз</b> - это объединение юридических лиц.
          Деятельность КФС направлена, прежде всего, на развитие и популяризацию
          всех разновидностей футбола в Кыргызской Республикe. КФС является
          единственно признанной ФИФА и АФК организацией, обеспечивающей
          контроль за развитием футбола в Кыргызстане.
        </p>
        <p>
          <b>Дата основания:</b> 2019
        </p>
        <p>
          <b>Предшественник:</b> Федерация футбола Кыргызской Республики
          (1992/2019)
        </p>
        <p>
          <b>Дата вступления в АФК:</b> 1994
        </p>
        <p>
          <b>Дата вступления в ФИФА:</b> 1994
        </p>
        <p>
          <b>Награды:</b> «Самая стремящаяся федерация года» (AFC Annual Awards
          2014)
        </p>
        <p>
          <b>Национальный стадион:</b> им. Д. Омурзакова
        </p>
        <p>
          <b>Дата открытия/реконструкции:</b> 1941, 1963, 1980-е, 2000-е
        </p>
        <p>
          <b>Освещение (люкс):</b> 1400
        </p>
        <p>
          <b>Размеры поля:</b> 105х75 м.
        </p>
      </div>
    </div>
  );
}
