import axios from "../../api/axios.news";
import React, { useEffect, useState } from "react";
import styles from "../../styles/gallery.module.sass";
import Masonry from "react-masonry-css";
import Head from "next/head";
import Loader from "../../components/Loader/Loader";
import Error from "../../components/Error/Error";

export default function galleries() {
  const [galleries, setGalleries] = useState(null);
  const [addMore, setAddMore] = useState(20);
  useEffect(() => {
    const getGalleries = async () => {
      try {
        const res = await axios.get(
          `/gallery?sort=publishedAt:DESC&pagination[pageSize]=${addMore}&populate=Image`
        );
        if (!res.data.data.Image) {
          throw new Error();
        }
        setGalleries([...res.data.data.Image]);
      } catch (error) {
        setGalleries("Error");
      }
    };
    getGalleries();
  }, []);
  if (galleries) {
    if (galleries === "Error") {
      return <Error />;
    } else {
      return (
        <>
          <Head>
            <title>Галерея</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <section className={styles.gallery__container}>
            <h2 className={styles.gallery__title}>Галерея</h2>
            <div className={styles.gallery}>
              <div className={styles.gallery__item}>
                <Masonry
                  breakpointCols={4}
                  className={styles.galleryItem__image}
                  columnClassName={styles.galleryItem__imageMasonry}
                >
                  {galleries.map(({ url, name, id }) => {
                    return <img src={url} alt={name} key={id} />;
                  })}
                </Masonry>
              </div>
            </div>
          </section>
        </>
      );
    }
  } else {
    return <Loader />;
  }
}
