import axios from "../../api/axios.news";
import React, { useEffect, useState } from "react";
import styles from "../../styles/gallery.module.sass";
import Masonry from "react-masonry-css";
import Head from "next/head";

export default function galleries() {
  const [galleries, setGalleries] = useState([]);
  const [addMore, setAddMore] = useState(10);
  useEffect(() => {
    const getGalleries = async () => {
      try {
        const res = await axios.get(
          `/gallery?sort=publishedAt:DESC&pagination[pageSize]=${addMore}&populate=Image`
        );
        if (!res.data) {
          throw new Error();
        }
        console.log(res);
        setGalleries([...res.data.data.Image]);
        console.log(gallery);
      } catch (error) {}
    };
    getGalleries();
  }, []);
  return (
    <>
      <Head>
        <title>Галерея</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.gallery__container}>
        <h2 className={styles.gallery__title}>Галерея</h2>
        <div className={styles.gallery}>
          <div className={styles.gallery__item}>
            <Masonry
              breakpointCols={4}
              className={styles.galleryItem__image}
              columnClassName={styles.galleryItem__imageMasonry}
            >
              {galleries.map(({ url, name, id }) => {
                return <img src={url} alt={name} key={id} />;
              })}
            </Masonry>
          </div>
        </div>
      </section>
    </>
  );
}
