import axios from "../../../api/axios.news";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../../../styles/kfu/documentation.module.sass";

export default function documentation() {
  const [data, setData] = useState([]);
  useEffect(() => {
    const getData = async () => {
      try {
        const res = await axios.get(`/trenerskoe-obrazovanies?populate=fail`);
        if (!res.data) {
          throw new Error();
        }
        setData(res.data.data);
      } catch (error) {}
    };
    getData();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Документы</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.main__title}>Документы</h1>
      <ul className={styles.info}>
        {data.map(({ name, id, fail }) => {
          return (
            <li key={id} className={styles.info__item}>
              <div className={styles.infoItem__icon}>
                <img src="/images/icons/pdf.png" alt={`pdf${name}`} />
              </div>
              <div className={styles.infoItem__des}>
                <span className={styles.infoItem__text}>{name}</span>
                <a href={fail[0].url}>Открыть</a>
              </div>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
