import Head from "next/head";
import styles from "../styles/Home.module.sass";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main__header}>
        <div className={styles.main__image}>
          <img src="/images/mainPhoto.jpg" alt="mainImage" />
        </div>
        <div className={styles.mainContent}>
          <div className={styles.main__title}>
            <h2 className={styles.titleItem}>
              КЫРГЫЗСТАНСКИЙ ФУТБОЛЬНЫЙ СОЮЗ ВМЕСТЕ В ВПЕРЕД!
            </h2>
            <h2 className={styles.titleItem}>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            </h2>
            <h2 className={styles.titleItem}>
              Далеко-далеко за словесными горами в стране гласных.
            </h2>
          </div>
          <p className={styles.main__text}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium, non perspiciatis atque nesciunt, autem iure unde ullam nihil harum nostrum odio.</p>
        </div>
      </main>
    </div>
  );
}
