import React, { useEffect, useRef, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.sass";
import LastNews from "../components/LastNews/LastNews";
import TeamTable from "../components/TeamTable/TeamTable.jsx";
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, EffectFade, Navigation, Pagination } from "swiper";
// import "./styles.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/effect-fade";
import "swiper/css/navigation";
import Sponsors from "../components/Sponsors/Sponsors";

export default function Home() {
  const [mainTitle, setMainTitle] = useState([
    {
      content: "fasdf f asdfs afwef dfg asdfge xdfasdf awe",
      active: true,
      id: 1,
    },
    {
      content: "asdfwe fadf awe fsadf asdwae fasf asf wef",
      active: false,
      id: 2,
    },
    {
      content: "asdfawef asef sdfcfgweaqft  FDGHRSEHG ER",
      active: false,
      id: 3,
    },
  ]);

  React.useEffect(() => {
    let interval = setInterval(() => {}, 1000);
    return () => clearInterval(interval);
  }, []);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main__header}>
        <Swiper
          effect={"fade"}
          navigation={true}
          autoplay={{
            delay: 8000,
            disableOnInteraction: false,
          }}
          pagination={{
            type: "progressbar",
            progressbarFillClass: styles.swiperPaginationProgressbarFill,
          }}
          modules={[EffectFade, Navigation, Pagination, Autoplay]}
          className={styles.main__image}
        >
          <SwiperSlide>
            <img src="/images/mainPhoto.jpg" alt="mainImage" />
          </SwiperSlide>
          <SwiperSlide>
            <img
              style={{ objectPosition: "0 -200px" }}
              src="/images/mainPhoto-1.jpg"
              alt="mainImage"
            />
          </SwiperSlide>
          <SwiperSlide>
            <img src="/images/mainPhoto-3.jpg" alt="mainImage" />
          </SwiperSlide>
          <SwiperSlide>
            <img
              style={{ objectPosition: "0 -200px" }}
              src="/images/mainPhoto-4.jpg"
              alt="mainImage"
            />
          </SwiperSlide>
        </Swiper>
        <div className={styles.mainContent}>
          <div className={styles.main__title}>
            <h3 className={styles.titleItem}>
              Lorem ipsum dolor sit amet consectetur adipisicing.
            </h3>
            <h3 className={styles.titleItem}>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            </h3>
            <h3 className={styles.titleItem}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum.
            </h3>
          </div>
          <p className={styles.main__text}>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
            Accusantium, non perspiciatis atque nesciunt, autem iure unde ullam
            nihil harum nostrum odio.
          </p>
        </div>
      </main>
      {/* ! ТАБЛИЦА */}
      <TeamTable />
      {/* ! Последние Новости */}
      <LastNews />
      {/* Спонсоры */}
      <Sponsors />
    </>
  );
}
