import React, { useEffect, useRef, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.sass";
import LastNews from "../components/LastNews/LastNews";
import TeamTable from "../components/TeamTable/TeamTable.jsx";
import Sponsors from "../components/Sponsors/Sponsors";
import Gallery from "../components/Gallery/Gallery";
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, EffectFade, Navigation, Pagination } from "swiper";
import cn from "classnames";
import Link from "next/link";
// import "./styles.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/effect-fade";
import "swiper/css/navigation";

export default function Home() {
  const [mainTitle, setMainTitle] = useState([
    {
      content: "Футбольный союз",
      active: true,
      id: 1,
    },
    {
      content: "Развивающий футбол в Кыргызстане",
      active: false,
      id: 2,
    },
    {
      content: "Вместе к победе!",
      active: false,
      id: 3,
    },
  ]);

  const [numIntervalIndex, setNumIntervalIndex] = useState({
    titleIndex: 0,
    nextTitleIndex: 1,
  });
  useEffect(() => {
    let forTitle = mainTitle.slice();
    let numIntervalIndexCopy = Object.assign({}, numIntervalIndex);
    let { titleIndex, nextTitleIndex } = numIntervalIndexCopy;
    let interval = setInterval(() => {
      if (forTitle[titleIndex].active === true) {
        forTitle[titleIndex].active = false;
        forTitle[nextTitleIndex].active = true;
        setMainTitle(forTitle);
      }
      if (titleIndex < 2) {
        titleIndex++;
      } else {
        titleIndex = 0;
      }
      if (nextTitleIndex < 2) {
        nextTitleIndex++;
      } else {
        nextTitleIndex = 0;
      }
      setNumIntervalIndex({
        titleIndex,
        nextTitleIndex,
      });
    }, 3000);
    return () => clearInterval(interval);
  }, []);
  const [mainHeaderShow, setMainHeaderShow] = useState(false);
  const handleScroll = () => {
    let scrollY = window.scrollY;
    if (scrollY > 20) {
      setMainHeaderShow(true);
    } else {
      setMainHeaderShow(false);
    }
  };
  useEffect(() => {
    handleScroll();
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main__header}>
        <Swiper
          effect={"fade"}
          navigation={true}
          autoplay={{
            delay: 6000,
            disableOnInteraction: false,
          }}
          pagination={{
            type: "progressbar",
            progressbarFillClass: styles.swiperPaginationProgressbarFill,
          }}
          modules={[EffectFade, Navigation, Pagination, Autoplay]}
          className={styles.main__image}
        >
          <SwiperSlide>
            <img src="/images/mainPhoto-1.jpg" alt="mainImage" />
          </SwiperSlide>
          <SwiperSlide>
            <img
              // style={{ objectPosition: "0 -200px" }}
              src="/images/mainPhoto-2.jpg"
              alt="mainImage"
            />
          </SwiperSlide>
          <SwiperSlide>
            <img
              style={{ objectPosition: "top" }}
              src="/images/mainPhoto-3.jpg"
              alt="mainImage"
            />
          </SwiperSlide>
          <SwiperSlide>
            <img
              style={{ objectPosition: "top" }}
              src="/images/mainPhoto-4.jpg"
              alt="mainImage"
            />
          </SwiperSlide>
        </Swiper>
        <div className={styles.mainContent}>
          <div className={styles.main__title}>
            {mainTitle.map(({ content, active, id }) => {
              return (
                <h3
                  key={id}
                  className={cn(styles.titleItem, {
                    [styles.mainTitleShow]: active,
                  })}
                >
                  {content}
                </h3>
              );
            })}
          </div>
          <p className={styles.main__text}>
            Кыргызский футбольный союз - это объединение юридических лиц.
            Деятельность КФС направлена, прежде всего, на развитие и
            популяризацию всех разновидностей футбола в Кыргызской Республикe.
            КФС является единственно признанной ФИФА и АФК организацией,
            обеспечивающей контроль за развитием футбола в Кыргызстане.
          </p>
          <Link href={"/about"}>
            <a className={styles.aboutLink__btn}>Подробнее</a>
          </Link>
        </div>
        <div
          className={cn(styles.homeNavigation, {
            [styles.mainHeaderShow]: mainHeaderShow,
          })}
        >
          <a href="#TournamentTable">Турнирная таблица</a>
          <a href="#LastNews">Последние новости</a>
        </div>
      </main>
      {/* ! ТАБЛИЦА */}
      <TeamTable />
      {/* ! Последние Новости */}
      <LastNews />
      {/* Галерея */}
      <Gallery />
      {/* Спонсоры */}
      <Sponsors />
    </>
  );
}
