import axios from "../../api/axios.news";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../../styles/tournament/tournament.module.sass";
import Link from "next/link";
import Loader from "../../components/Loader/Loader";
import Error from "../../components/Error/Error";
export default function tournament() {
  const [data, setData] = useState(null);
  useEffect(() => {
    const getData = async () => {
      try {
        const res = await axios.get(`/tournaments?populate=image`);
        if (!res.data) {
          throw new Error();
        }
        setData(res.data.data);
      } catch (error) {
        setData("Error");
      }
    };
    getData();
  }, []);
  if (data) {
    if (data === "Error") {
      return <Error />;
    } else {
      return (
        <div className={styles.container}>
          <Head>
            <title>Турниры</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <h1 className={styles.main__title}>Турниры</h1>
          <p className={styles.main__content}>
            Соревнования по футболу, как и в любом другом виде спорта — важная
            составляющая игры. Соревнование организуется федерацией, для каждого
            турнира составляется регламент, в котором обычно определяют состав
            участников, схему турнира, правила определения победителя при
            равенстве очков и какие-то отклонения от правил, например количество
            замен. Соревнования делятся на внутренние и международные, которые в
            свою очередь разделяются на клубные и национальных сборных.
            Футбольные турниры собирают десятки тысяч зрителей на трибунах
            стадиона и многомиллионные аудитории по телевидению.
          </p>
          <ul className={styles.tournaments}>
            {data.map(({ title, text, image, id }) => {
              return (
                <Link href={`/tournament/${id}`} key={id}>
                  <a className={styles.tournaments__item}>
                    <div className={styles.tournamentsItem__image}>
                      <img src={image.url} alt={image.name} />
                    </div>
                    <h3 className={styles.tournamentsItem__title}>{title}</h3>
                  </a>
                </Link>
              );
            })}
          </ul>
        </div>
      );
    }
  } else {
    return <Loader />;
  }
}
