import axios from "../../../api/axios.news";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../../../styles/kfu/kfuSecretariat.module.sass";

export default function kfuSecretariat() {
  const [secretariat, setSecretariat] = useState([]);
  useEffect(() => {
    const getSecretariat = async () => {
      try {
        const res = await axios.get(`/secretariats?populate=image`);
        if (!res.data) {
          throw new Error();
        }
        setSecretariat(res.data.data);
      } catch (error) {}
    };
    getSecretariat();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Cекретариат</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.main__title}>Cекретариат КФС</h1>
      <ul className={styles.content}>
        {secretariat.map(({ name, rank, id, image }) => {
          return (
            <li className={styles.content__item} key={id}>
              <div className={styles.contentItem__image}>
                <img src={image.url} alt={image.name} />
              </div>
              <span className={styles.contentItem__rank}>{rank}</span>
              <h3 className={styles.contentItem__title}>{name}</h3>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
