import axios from "../../api/axios.news";
import React, { useEffect, useState } from "react";
import styles from "../../styles/allNews.module.sass";
import Link from "next/link";
import Head from "next/head";

export default function index() {
  const [news, setNews] = useState([]);
  useEffect(() => {
    const getLastNews = async () => {
      try {
        const res = await axios.get(
          "/news-id?sort=publishedAt:DESC&populate=image"
        );
        if (!res.data) {
          throw new Error();
        }
        setNews([...res.data.data]);
      } catch (error) {}
    };
    getLastNews();
  }, []);
  return (
    <>
      <Head>
        <title>Все Новости</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.allNews}>
        <h2 className={styles.allNews__title}>Все Новости</h2>
        <ul className={styles.lastNews__container}>
          {news.map(({ postDescription, postDate, image, id }) => {
            return (
              <li key={id} className={styles.lastNews__cart}>
                <img
                  className={styles.header__img}
                  src={image.url}
                  alt={image.name}
                />
                <div className={styles.newsCart__content}>
                  <p>{postDescription}</p>
                  <div className={styles.newsCart__contentDes}>
                    <span className={styles.cartData}>{postDate}</span>
                    <Link href={`/allNews/${id}`}>
                      <button className={styles.cart__btn}>
                        Подробнее <img src="/images/icons/Vector.svg" alt="#" />
                      </button>
                    </Link>
                  </div>
                </div>
              </li>
            );
          })}
        </ul>
      </header>
    </>
  );
}
