import axios from "../../api/axios.news";
import React, { useEffect, useState } from "react";
import styles from "../../styles/allNews.module.sass";
import Link from "next/link";
import Head from "next/head";
import Masonry from "react-masonry-css";

export default function allNews() {
  const [postWithImage, setPostWithImage] = useState([]);
  const [usualPost, setUsualPost] = useState([]);
  const [addNews, setAddNews] = useState(10);
  useEffect(() => {
    const getLastNews = async () => {
      try {
        const res = await axios.get(
          `/news-id?sort=publishedAt:DESC&pagination[pageSize]=${addNews}&populate=image`
        );
        if (!res.data) {
          throw new Error();
        }
        let postWithImageCopy = [];
        let usualPostCopy = [];
        res.data.data.forEach((item) => {
          let { width } = item.image;
          if (width > 1920) {
            postWithImageCopy.push(item);
          } else {
            usualPostCopy.push(item);
          }
        });
        setPostWithImage([...postWithImageCopy]);
        setUsualPost([...usualPostCopy]);
      } catch (error) {}
    };
    getLastNews();
  }, [addNews]);
  return (
    <>
      <Head>
        <title>Все Новости</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.allNews__container}>
        <h2 className={styles.allNews__title}>Все Новости</h2>
        <main className={styles.content}>
          <ul className={styles.usualPost__list}>
            {usualPost.map(({ postDescription, postDate, id }) => {
              return (
                <Link key={id} href={`/allNews/${id}`}>
                  <li className={styles.usualPost__item}>
                    <span className={styles.cartData}>{postDate}</span>
                    <p>{postDescription}</p>
                  </li>
                </Link>
              );
            })}
          </ul>
          <Masonry
            breakpointCols={2}
            className={styles.postWithImage__list}
            columnClassName={styles.myMasonryGrid_column}
          >
            {postWithImage.map(({ postDescription, image, id, className }) => {
              return (
                <Link key={id} href={`/allNews/${id}`}>
                  <li className={styles.postWithImage__item} id={className}>
                    <img src={image.url} alt={image.name} />
                    <div className={styles.postWithImage__content}>
                      <p>{postDescription}</p>
                    </div>
                  </li>
                </Link>
              );
            })}
          </Masonry>
        </main>
        <button
          className={styles.addMoreNews__btn}
          onClick={() => setAddNews(addNews + 5)}
        >
          Добавить еще
        </button>
      </header>
    </>
  );
}
